### ISSUE TITLE
Locking Period not decreasing

### ISSUE THREAD

**Issue by anyela-sweden** [curvance-web/app-community#1]
Some days ago, i had this positions : 
<img width="1511" alt="Screenshot 178" src="https://github.com/user-attachments/assets/7425a39b-6cb9-4cbd-b418-fe216cb1ae29">
As you can see, 11M 22D 17H

I just opened a new position Now: 
<img width="1528" alt="Screenshot 179" src="https://github.com/user-attachments/assets/06d10026-eb60-4be5-81f3-6b01dfac3359">

and the lock period are all the same. 
So i wonder if the locking period is really decreasing proper ??

**Comment by joaom00** [comment]
hey this is working as expected

### Before
![image](https://github.com/user-attachments/assets/b34d412d-8aa1-437c-ac1b-1babed50032b)

### Now
![image](https://github.com/user-attachments/assets/1d89b8c1-1ae4-4bdd-acbf-4d2669610ee8)
