### ISSUE TITLE
Public Berachain Shows Incomplete while is Completed 100%

### ISSUE THREAD

**Issue by anyela-sweden** [curvance-web/app-community#27]
On the feedback section, you can see the following : 
<img width="1156" alt="Screenshot 209" src="https://github.com/user-attachments/assets/e500970f-f2b3-465d-8286-b2ede8dc419f">

while on Notifications Menu is the following : 
<img width="529" alt="Screenshot 208" src="https://github.com/user-attachments/assets/3456519d-0f3d-4452-bc63-ee63a37694dd">

**Comment by joaom00** [comment]
@anyela-sweden the `incomplete` badge in the feedback modal means that the feedback has not been submitted yet.

**Comment by anyela-sweden** [comment]
You are totally right. Maybe we should revise the wording to make it even clearer.
"Submitted", " Testnet in progress", "Ready to Submit"
??
