### ISSUE TITLE
Movement UI - Update Banner Graphic and Wallet Balance Denomination

### ISSUE THREAD

**Issue by 0xTAY** [curvance-web/app-community#39]
1. Update Banner from Berachain to Movement graphic.

![Screenshot 2024-09-03 at 9 29 25 PM](https://github.com/user-attachments/assets/05964cdc-370c-4fd3-bb8d-8bb6530707a2)

2. Update Wallet Balance from ETH to MOVE 

![Screenshot 2024-09-03 at 9 29 40 PM](https://github.com/user-attachments/assets/6a66264e-d753-4f71-8a1f-42591103c537)

**Comment by joaom00** [comment]
Done
