### ISSUE TITLE
Movement Faucet - Updating copy to reflect MEVM

### ISSUE THREAD

**Issue by 0xTAY** [curvance-web/app-community#40]
"The Movement Network testnet is a Proof-of-Stake testnet where Move application developers can test their smart contracts without spending real MOVE tokens. Click [here](https://faucet.movementlabs.xyz/) to learn more about faucets."

![Screenshot 2024-09-03 at 9 34 10 PM](https://github.com/user-attachments/assets/b6ca9b42-461c-4f14-896b-4a445574a284)

**Comment by joaom00** [comment]
Done
