### ISSUE TITLE
Movement - Block explorer 404 when clicking view transaction from wallet 

### ISSUE THREAD

**Issue by 0xTAY** [curvance-web/app-community#41]
When you click 'view on block explorer' in your wallet it brings you to a 404 page seen in the screenshot below.

![Screenshot 2024-09-03 at 9 41 07 PM](https://github.com/user-attachments/assets/f4772aa1-cf51-427b-80e6-7c7430646145)

Incorrect URL: https://explorer.devnet.imola.movementlabs.xyz/tx/0xe6193c99fcdd582885d6ad1efd581ceb11f1013712653ca481488a14a4cc1259

Correct URL: https://explorer.devnet.imola.movementlabs.xyz/#/txn/19837859/userTxnOverview?network=testnet

**Comment by Caixetadev** [comment]
Done
