### ISSUE TITLE
Movement - Task groups do not appear for Movement Network 

### ISSUE THREAD

**Issue by 0xTAY** [curvance-web/app-community#42]
Berachain tasks group / feedback form should be copied over for Movement. 

![Screenshot 2024-09-03 at 9 46 25 PM](https://github.com/user-attachments/assets/a9d050af-ddeb-4cc8-b2af-418e3be08fe8)

**Comment by joaom00** [comment]
It seems that the tasks for Movement have not been added to the backend. I will ask Lucas when it will be added.
