### ISSUE TITLE
Movement - Infinite collateral displaying in borrow modal 

### ISSUE THREAD

**Issue by 0xTAY** [curvance-web/app-community#51]
1. Deposit collateral 
2. Go to Borrow tab 
3. Borrow modal shows Total collateral amount as "∞ USDC" 

![Screenshot 2024-09-04 at 12 15 45 PM](https://github.com/user-attachments/assets/26a2a207-1968-4f4c-99c9-83e53f5e1a57)

**Comment by joaom00** [comment]
Done
