### ISSUE TITLE
Movement [CRITICAL] - Withdrawing collateral bricks website 

### ISSUE THREAD

**Issue by 0xTAY** [curvance-web/app-community#52]
1. Deposit collateral
2. Wait 20 minutes
3. Try to withdraw collateral or uncollateralized deposits but unable to click continue 

Entire site freezes and you need to manually refresh just to get back into the dapp 

![Screenshot 2024-09-04 at 12 28 53 PM](https://github.com/user-attachments/assets/3f3cde49-9079-4bbf-ac50-dbd5a0dc87fe)

**Comment by joaom00** [comment]
Done
