### ISSUE TITLE
Movement - Clicking tasks in the Notifications Menu does not redirct you to the task/action

### ISSUE THREAD

**Issue by 0xTAY** [curvance-web/app-community#56]
Clicking these tasks should redirect you to the right page / trigger the action like it does on the other netowrks. 

![Screenshot 2024-09-04 at 12 48 00 PM](https://github.com/user-attachments/assets/cc556627-cc5a-4f57-8fb7-435a17f51835)

**Comment by Caixetadev** [comment]
done
