### ISSUE TITLE
Movement - Mint tokens task not completing after minting tokens

### ISSUE THREAD

**Issue by 0xTAY** [curvance-web/app-community#60]
1. Hit claim all from Faucet
2. Transaction posts succesfully
3. It doesn't check off the task in the task menu

![Screenshot 2024-09-04 at 8 35 59 PM](https://github.com/user-attachments/assets/17a1fb86-24c5-455f-99f7-8fbf0da75c2b)

**Comment by joaom00** [comment]
can you try again? is working here
