### ISSUE TITLE
Switch Network Features Not working

### ISSUE THREAD

**Issue by anyela-sweden** [curvance-web/app-community#62]
When i reach this page : https://staging-app.curvance.com/
i got this page  : 
 
<img width="1252" alt="Screenshot 395" src="https://github.com/user-attachments/assets/36682b82-7344-4cad-8dce-f5cf05573567">

trying to change network with the button "Switch Network" but nothing happen, button does anu function here.

<img width="1274" alt="Screenshot 396" src="https://github.com/user-attachments/assets/bab3742e-eec3-455b-b033-d3c4c6b08f77">

How to fix? 
<img width="395" alt="Screenshot 397" src="https://github.com/user-attachments/assets/5cfc5aa9-ca62-4698-a0a6-a5e91ea791a9">
Disconnect all account from the website
<img width="409" alt="Screenshot 398" src="https://github.com/user-attachments/assets/13d1af98-15bd-408f-b117-5ff0bb4ec878">

Connect Accounts and refresh the page "hard refresh"

Now it works...
<img width="1442" alt="Screenshot 399" src="https://github.com/user-attachments/assets/4d55c5d3-9f5e-43bc-9f19-97193f0284db">

**Comment by joaom00** [comment]
@anyela-sweden can you try again? seems to be working here
