### ISSUE TITLE
Movement [Critical] - Error when trying to Repay 

### ISSUE THREAD

**Issue by 0xTAY** [curvance-web/app-community#68]
1. Borrow 
2. Wait 20 mins
3. Go to repay 
4. Approve transaction
5. Click continue and you get the error before it asks you to sign the transaction 

![Screenshot 2024-09-04 at 10 40 33 PM](https://github.com/user-attachments/assets/fbe7ecea-c7ad-47b8-a270-8aa628375356)

**Comment by joaom00** [comment]
This was actually a bug, but it has been fixed.
