### ISSUE TITLE
Button Repay are not enabling even after waiting time.....

### ISSUE THREAD

**Issue by anyela-sweden** [curvance-web/app-community#71]
I want to Repay..... but

<img width="752" alt="Screenshot 412" src="https://github.com/user-attachments/assets/a61d42e2-e8c3-4131-8f5f-6dbb0212f007">

but a pop up showing me "wait 0 minutes" 
ok, i wait....

but....
<img width="773" alt="Screenshot 414" src="https://github.com/user-attachments/assets/7d4103a0-8777-4e2a-9f83-828b328619a3">

2 minutes later.. still the same, the button should be enable now....

now it's 8 minutes later and still the same....
i refresh the page manually ....
same ...
why is it wait 0 minutes not accurate here????

**Comment by joaom00** [comment]
should be fixed
