### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation

### ISSUE THREAD

**Issue by anyela-sweden** [curvance-web/app-community#72]
on main page : https://staging-app.curvance.com/

Clicking on the Active Debt : 

https://github.com/user-attachments/assets/28535170-b8d4-4d97-a7e2-598fdd7be38c

error : 
<img width="759" alt="Screenshot 415" src="https://github.com/user-attachments/assets/8619514d-4def-4d08-9d83-8e2aca0cf0e3">

**Comment by joaom00** [comment]
Done
