### ISSUE TITLE
General App (Live) - Can't scroll down in Lock screen unless cursor is in main area

### ISSUE THREAD

**Issue by MisuFubu** [curvance-web/app-community#79]
When I go to the Lock page, I can't scroll down unless my mouse is over the main lock information area in the centre of the page. If I try to scroll while my cursor is in the black area on the sides, I can't scroll -- please fix. In all the other parts of the testnet, if I try to scroll in the black empty area on the side, it works -- this is good.

**Comment by joaom00** [comment]
Done
